name: ethics
recipe: 'drupal8'
config:
  php: '8.1'
  via: 'nginx'
  webroot: './web'
  xdebug: true
  config:
    php: lando.php.ini
services:
  appserver:
    build_as_root:
      - apt-get update -y
      - apt-get install libxslt1-dev -y
      - docker-php-ext-install xsl
      - docker-php-ext-enable xsl
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://ethics.lndo.site"
  pma:
    type: phpmyadmin
